// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pearlis-layouts/AsymmetricSplit.tsx": () => import("../components/mockups/pearlis-layouts/AsymmetricSplit.tsx"),
  "./components/mockups/pearlis-layouts/EditorialStack.tsx": () => import("../components/mockups/pearlis-layouts/EditorialStack.tsx"),
  "./components/mockups/pearlis-layouts/GridFirstDense.tsx": () => import("../components/mockups/pearlis-layouts/GridFirstDense.tsx")
};
